default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: taobao_development


test:
  <<: *default
  database: taobao_test
  host: 192.168.99.100
  password: taobao


production:
  <<: *default
  database: taobao_production


